stages:
 - ca_and_test
 - deploy
# - migrate
 - cleanup

include:
  - project: gitlab-ci/templates
    ref: master
    file: werf-1.2.gitlab-ci.yml

variables:
  GIT_SUBMODULE_STRATEGY: recursive

.base_deploy:
  stage: deploy
  extends: .werf_converge
  script:
    - build-env -f .env.example -e $CI_ENVIRONMENT_NAME > .env ; cp .env .helm/.env
    - werf converge
      --namespace $KUBE_NAMESPACE
      --set gitlab.build=$CI_JOB_ID
      --set gitlab.app=$CI_PROJECT_PATH_SLUG
      --set gitlab.env=$CI_ENVIRONMENT_SLUG
      --set imageCredentials.registry=$CI_REGISTRY
      --set imageCredentials.username=$CI_DEPLOY_USER
      --set imageCredentials.password=$CI_DEPLOY_PASSWORD
      --set ingress.host="$K8S_INGRESS_HOST"
      --set newrelic.daemon.enabled._default="$NEWRELIC_ENABLED"

.base_stop:
  stage: cleanup
  extends: .werf_dismiss

before_script:
  - cd libs
  - composer install
  - cd ..

code style:
  stage: ca_and_test
  image: gitlab.treeum.net:5005/docker-library/sd-ci-tools:latest
  script:
    - phpcs --standard=/opt/CoderAssistant/resources/Festi/ruleset.xml -d memory_limit=1024M --extensions=php --error-severity=1 --warning-severity=8 --ignore="themes/**, core/public/**, libs/vendor/**, libs/sentry/**, core/.phan/**, .phan/**, libs/log/**, db/**" ./
  except:
    refs:
      - schedules
  tags:
    - docker

test:
  stage: ca_and_test
  image: gitlab.treeum.net:5005/docker-library/sd-ci-tools:latest
  script:
  - /etc/init.d/postgresql start
  - su postgres -c "psql -c 'CREATE USER gitlab_user WITH SUPERUSER;'"
  - su postgres -c "psql -d postgres -U gitlab_user -c 'CREATE DATABASE gitlab_i_system;'"
  - su postgres -c "psql -d postgres -U gitlab_user -c 'CREATE DATABASE gitlab_i_test;'"
  - cd tests
  - phpunit --coverage-text
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  cache:
    paths:
      - tests/reports/
  except:
    refs:
      - schedules
  tags:
    - docker

code analysis:
  stage: ca_and_test
  image: gitlab.treeum.net:5005/docker-library/sd-ci-tools:latest
  script:
    -  /vendor/bin/phan  --config-file .phan/config.php
  except:
    refs:
      - schedules
  tags:
    - docker

deploy:review1:
  extends: .base_deploy
  resource_group: review1
  variables:
    K8S_INGRESS_HOST: internal-api.$CI_ENVIRONMENT_SLUG.sd-app.net
  environment:
    name: review1
    action: start
    url: https://internal-api.$CI_ENVIRONMENT_SLUG.sd-app.net
    on_stop: "stop:review1"
    auto_stop_in: 3 days
  only:
    refs:
      - /^feature\/.+/
      - develop
      - master

deploy:stage:
  extends: .base_deploy
  resource_group: stage
  variables:
    K8S_INGRESS_HOST: internal-api.$CI_ENVIRONMENT_SLUG.sd-app.net
  environment:
    name: stage
    action: start
    url: https://internal-api.$CI_ENVIRONMENT_SLUG.sd-app.net
    on_stop: "stop:stage"
  only:
    refs:
      - /^hotfix\/.+/
      - develop
      - master

deploy:prod:
  extends: .base_deploy
  resource_group: prod
  variables:
    K8S_INGRESS_HOST: api.internal.salesdoubler.com.ua
  environment:
    name: prod
    action: start
    url: https://api.internal.salesdoubler.com.ua
  only:
    refs:
      - tags

stop:review1:
  extends: .base_stop
  resource_group: review1
  environment:
    name: review1
    action: stop
  only:
    refs:
      - /^feature\/.+/

stop:stage:
  extends: .base_stop
  resource_group: stage
  environment:
    name: stage
    action: stop
  only:
    refs:
      - /^hotfix\/.+/
      - develop
      - master

stop:prod:
  extends: .base_stop
  resource_group: prod
  environment:
    name: prod
    action: stop
  only:
    refs:
      - tags
    variables:
      - $ENABLE_DESTROY == "YES"

#migration dev:
#  stage: migrate
#  only:
#    - develop
#    - /^feature.*$/
#  script:
#    - cd $TARGET_STAGING_DIR/libs
#    - php vendor/bin/phinx migrate -e main
#  when: manual
#
